#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

if [ "$1" == "describe" ]; then
   echo "Create a snapshot of the current workdir and push it to the cloud."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud snapshot"
    echo
    echo "Create a snapshot of the current workdir and push it to the cloud."
    echo
    exit 0
fi

GIT_TOP_LEVEL=$(git rev-parse --show-toplevel)
cd "$GIT_TOP_LEVEL"
MAIN_GIT_DIR=$(git rev-parse --git-dir)
CLOUD_GIT_DIR="${MAIN_GIT_DIR}/worktrees/cloud"
BRANCH="${GIT_CLOUD_SNAPSHOT_BRANCH_PREFIX}-$(hostname)"
LOCAL_BRANCH=$(git rev-parse --abbrev-ref main-worktree/HEAD)
LAST_COMMIT=$(git rev-parse HEAD)

if [ ! -e "${MAIN_GIT_DIR}/worktrees/cloud" ]; then
    echo "== Setting up cloud worktree"
    mkdir -p "${MAIN_GIT_DIR}/x-cloud/worktree"

    git worktree add "${MAIN_GIT_DIR}/x-cloud/worktree/cloud" -b "${BRANCH}" --no-checkout
    # Consider instead creating an orphan branch instead. I'm unsure about the differences it will cause,
    # but it seems to increase time for first sync a lot.
    #
    # git worktree add "${MAIN_GIT_DIR}/x-cloud/worktree/cloud" --no-checkout
    # git -C "${MAIN_GIT_DIR}/x-cloud/worktree/cloud" switch --orphan "${BRANCH}"
    #
    git -C "${MAIN_GIT_DIR}/x-cloud/worktree/cloud" commit -m "git-cloud initial $(hostname) ${LOCAL_BRANCH} ${CLEAN}" --allow-empty --no-gpg-sign
fi

echo "== Staging modifications into cloud worktree"
git --git-dir "${CLOUD_GIT_DIR}" add -A
sleep 1
while [ -n "$(git --git-dir "${CLOUD_GIT_DIR}" diff --quiet --cached)" -o "$LOCAL_BRANCH" != "$(git rev-parse --abbrev-ref main-worktree/HEAD)" ]; do
    echo "Note: files or branch changing while working; updating."
    LOCAL_BRANCH=$(git rev-parse --abbrev-ref main-worktree/HEAD)
    LAST_COMMIT=$(git rev-parse HEAD)
    git --git-dir "${CLOUD_GIT_DIR}" add -A
    sleep 1
done

CHANGE=$(git --git-dir "${CLOUD_GIT_DIR}" diff --shortstat main-worktree/HEAD)
if [ -z "$CHANGE" ]; then
    CLEAN="clean"
else
    CHANGE='

    '"$CHANGE"
    CLEAN="unclean"
fi

# Lets NOT merge histories; instead handle this when applying changes back
#git --git-dir "${CLOUD_GIT_DIR}" merge main-worktree/HEAD --no-ff --no-gpg-sign -m "git-cloud merge $(hostname) ${LOCAL_BRANCH} $(date -R)" --allow-unrelated-histories

if [ -n "$(git --git-dir "${CLOUD_GIT_DIR}" diff --name-only --cached)" ]; then
    echo "== Commiting changes"
    git --git-dir "${CLOUD_GIT_DIR}" commit -m "git-cloud commit $(hostname) ${LOCAL_BRANCH} ${LAST_COMMIT} ${CLEAN} ${CHANGE}" --no-gpg-sign
else

    LAST_MSG=$(git --git-dir "${CLOUD_GIT_DIR}" log -1 --pretty=%B)
    LAST_SNAP_CLIENT=$(cut -d ' ' -f 1 <<< "$LAST_MSG")
    if [ "$LAST_SNAP_CLIENT" == "git-cloud" ]; then
        LAST_SNAP_BRANCH=$(cut -d ' ' -f 4 <<< "$LAST_MSG")
        LAST_SNAP_COMMIT=$(cut -d ' ' -f 5 <<< "$LAST_MSG")
        echo "== Check:" "$LAST_SNAP_BRANCH" != "$LOCAL_BRANCH" -o "$LAST_COMMIT" != "$LAST_SNAP_COMMIT"
        if [ "$LAST_SNAP_BRANCH" != "$LOCAL_BRANCH" -o "$LAST_COMMIT" != "$LAST_SNAP_COMMIT" ]; then
            echo "== Commiting empty due to branch or top commit change"
            git --git-dir "${CLOUD_GIT_DIR}" commit --allow-empty -m "git-cloud commit $(hostname) ${LOCAL_BRANCH} ${LAST_COMMIT} ${CLEAN} ${CHANGE}" --no-gpg-sign
        fi
    else
        echo "== Commiting empty commit due to unparseable previous message"
        git --git-dir "${CLOUD_GIT_DIR}" commit --allow-empty -m "git-cloud commit $(hostname) ${LOCAL_BRANCH} ${LAST_COMMIT} ${CLEAN} ${CHANGE}" --no-gpg-sign
    fi

    echo "== No changes to commit"
fi

if ! git show-branch "${GIT_CLOUD_REMOTE_NAME}/${BRANCH}" >& /dev/null; then

    echo "== Upstream branch does not exist, pushing with --set-upstream"
    git --git-dir "${CLOUD_GIT_DIR}" push --follow-tags --set-upstream "${GIT_CLOUD_REMOTE_NAME}" "${BRANCH}"

else

    if [ -n "$(git --git-dir "${CLOUD_GIT_DIR}" cherry | head -n 1)" ]; then
        echo "== Changes made, pushing to cloud"
        git --git-dir "${CLOUD_GIT_DIR}" push --follow-tags
    else
        echo "== No commits to push to cloud"
    fi

fi
exit 0

