#!/bin/bash

set -e

source internal-git-cloud-read-config

if [ "$1" == "describe" ]; then
   echo "Continously create checkpoints of the whole repotree."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud daemon"
    echo
    echo "Continously create checkpoints of the whole repotree."
    echo
    exit 0
fi

while [ "0" == "0" ]; do
    if ! nice git-cloud-snapshot; then
        echo "== Error on git cloud snapshot. Delaying 3600 seconds and retrying."
        sleep 3600
    fi
    echo
    echo "==== Snapshot cycle done (waiting)"
    echo
    sleep 120
done
