#!/bin/bash

set -e

source internal-git-cloud-read-config

if [ "$1" == "describe" ]; then
   echo "Init one or more subrepositories"
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud repoinit <one or more subrepos>"
    echo
    echo "Initializes one or more subrepos."
    echo ""
    exit 0
fi

if [ -z "${GIT_CLOUD_ROOT}" ]; then
    echo "fatal: not a git cloud repository (or any of the parent directories): .git-cloud" >&2
    exit 1
fi

cd "${GIT_CLOUD_ROOT}"
git submodule init "$@"
