#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

CONNSHARE="auto"
while [ 1 == 1 ]; do
    if [ "$1" == "--cs-ask" ]; then
        CONNSHARE="ask"
        shift 1
    elif [ "$1" == "--cs-auto" ]; then
        CONNSHARE="auto"
        shift 1
    elif [ "$1" == "--cs-off" ]; then
        CONNSHARE="off"
        shift 1
    else
        break
    fi
done

if [ "$1" == "describe" ]; then
   echo "Run git pull on all repos in a cloud repotree."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud pull [--cs-ask|--cs-auto|--cs-off]"
    echo
    echo
    echo "    --cs-ask (default): set up ssh connection sharing, but ask each time it is used (safer on multiuser machines)"
    echo
    echo "    --cs-auto: set up ssh connection sharing, and skip passwords (unsafe if someone else can access the socket)."
    echo
    echo "    --cs-off: don't set up ssh connection sharing"
    echo
    echo "Run git pull on all repos in a cloud repotree."
    echo
    exit 0
fi

source internal-git-cloud-connshare
internal-git-cloud-load-keys "$CONNSHARE"

find . -name ".git" -prune | while read LINE; do
    REPOPATH=$(dirname "$LINE")
    TRACKING=$(git -C "$REPOPATH" rev-parse --abbrev-ref --symbolic-full-name @{u})
    REMOTE=$(git -C "$REPOPATH" remote get-url "${TRACKING%%/*}")
    CLOUD_REMOTE=$(git -C "$REPOPATH" remote get-url cloud)
    if [ "$REMOTE" == "$CLOUD_REMOTE" ]; then
        echo "== Pulling from: $REPOPATH"
        git -C "$REPOPATH" pull
    fi
done

