#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

if [ "$1" == "describe" ]; then
   echo "Continously create checkpoints of the whole repotree."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud daemon"
    echo
    echo "Continously create checkpoints of the whole repotree."
    echo
    exit 0
fi

internal-git-cloud-load-keys

while [ "0" == "0" ]; do
    git cloud snaptree
    sleep 120
done
