#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

if [ "$1" == "describe" ]; then
   echo "Show the difference between the working tree and the latest cloud checkpoint(s)."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud status [--no-fetch] [--cs-ask|--cs-auto|--cs-off]"
    echo
    echo "Show the difference between the working tree and the latest cloud checkpoint."
    echo ""
    echo "Options:"
    echo "  --no-fetch: base output on what is already known about the"
    echo "              cloud remote without starting with a fetch operation."
    echo
    exit 0
fi

# Ascend until we find a .git-cloud
while [ "$(pwd)" != "/" ]; do
  if [ -f ".git-cloud" ]; then
      break
  fi
  cd ..
done
if [ ! -f ".git-cloud" ]; then
    echo "Git cloud pull must be run inside a git cloud repotree." >&2
    exit 1
fi

find . -name ".git" -prune | while read LINE; do
    REPOPATH=$(dirname "$LINE")
    echo
    echo "== REPO: $REPOPATH"

    (cd "$REPOPATH"
     git-cloud-statrepo
    )
done
