#!/bin/bash

set -e

source internal-git-cloud-read-config

if [ "$1" == "describe" ]; then
   echo "Create snapshots of all repos in a repotree."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud snaptree"
    echo
    echo "Create snapshots of all repos in a repotree."
    echo
    exit 0
fi

# Ascend until we find a .git-cloud
cd "$(pwd -P)"
while [ "$(pwd -P)" != "/" ]; do
  if [ -f ".git-cloud" ]; then
      break
  fi
  cd ..
done
if [ ! -f ".git-cloud" ]; then
    echo "Git cloud pull must be run inside a git cloud repotree." >&2
    exit 1
fi

echo "======== Looping through all repos"
find . -name ".git" -prune | while read LINE; do
    DIR=$(dirname "$LINE")
    echo "==== Syncing: $DIR"
    ( cd "$DIR"
      git-cloud-snaprepo
    )
done
