#!/bin/bash

set -e

source internal-git-cloud-read-config

if [ "$1" == "describe" ]; then
   echo "Add a new repo to cloud master repo."
   exit 0
elif [ "$1" == "help" -o "$#" -lt 2 -o "$#" -gt 3 ]; then
    echo
    echo "Usage: git cloud add [<local path> [<cloud name> [remote repo]]]"
    echo
    echo "Add a new repo at <local path>, either as an empty repo or cloning <remote repo>, if given."
    echo ""
    exit 0
fi

if [ -z "${GIT_CLOUD_ROOT}" -o -z "${GIT_CLOUD_HOST}" ]; then
    echo "fatal: not a git cloud repository (or any of the parent directories): .git-cloud" >&2
    exit 1
fi

if [ -z "$1" ]; then
    LOCAL_PATH="."
    CLOUD_NAME="$(basename "$(pwd)")"
else
    LOCAL_PATH="./$1"
    LOCAL_PATH="${PROGRAM/#.\/\//\/}"
    CLOUD_NAME="$(basename "$LOCAL_PATH")"
fi
if [ -n "$2" ]; then
    CLOUD_NAME="$2"
fi
CLOUD_NAME="${CLOUD_NAME%.git}"
REMOTE_REPO="$3"

if [ -n "$REMOTE_REPO" ]; then
    git clone "${REMOTE_REPO}" "${LOCAL_PATH}"
    mkdir -p "${GIT_CLOUD_REPOCONFIG}/repos/${CLOUD_NAME}/remotes"
    echo -e "${REMOTE_REPO}" > "${GIT_CLOUD_REPOCONFIG}/repos/${CLOUD_NAME}/remotes/origin.fetch"
    echo -e "${REMOTE_REPO}" > "${GIT_CLOUD_REPOCONFIG}/repos/${CLOUD_NAME}/remotes/origin.push"
fi

echo "$GIT_CLOUD_HOST" "$RHOST"
echo "CHECK2:" $GIT_SSH_COMMAND -O check "$GIT_CLOUD_HOST"
if $GIT_SSH_COMMAND -O check "$GIT_CLOUD_HOST" >& /dev/null; then
    echo "Info: connection sharing already active."
else
    echo "NO!"
fi
exit 0

echo ${GIT_SSH_COMMAND} "${GIT_CLOUD_HOST}" bash -c "echo -n \"\"; if [ ! -e \"${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}.git\" ]; then git init -q --bare --initial-branch=main \"${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}.git\"; fi"
#${GIT_SSH_COMMAND} "${GIT_CLOUD_HOST}" bash -c "echo -n \"\"; if [ ! -e \"${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}.git\" ]; then git init -q --bare --initial-branch=main \"${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}.git\"; fi"
${GIT_SSH_COMMAND} "${GIT_CLOUD_HOST}" bash -c "echo -n \"\"; if [ ! -e \"${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}.git\" ]; then hostname; else echo why; fi"

if [ -n "$REMOTE_REPO" ]; then
    echo git -C "${LOCAL_PATH}" remote add cloud "${GIT_CLOUD_HOST}:${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}"
    git -C "${LOCAL_PATH}" remote add cloud "${GIT_CLOUD_HOST}:${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}"
    git push cloud
else
    echo git clone -q --origin cloud "${GIT_CLOUD_HOST}:${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}" "${LOCAL_PATH}"
    git clone -q --origin cloud "${GIT_CLOUD_HOST}:${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}" "${LOCAL_PATH}"
    git -C "${LOCAL_PATH}" commit --allow-empty -m "Initial commit"
    git -C "${LOCAL_PATH}" push
fi
echo git submodule add "${GIT_CLOUD_HOST}:${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}" "${LOCAL_PATH}"
git submodule add "${GIT_CLOUD_HOST}:${GIT_CLOUD_PATH}.repos/${CLOUD_NAME}" "${LOCAL_PATH}"
