#!/bin/bash

set -e

source internal-git-cloud-read-config

if [ "$1" == "describe" ]; then
   echo "Create a new cloud repo and clone it into the local directory."
   exit 0
elif [ "$1" == "help" -o "$#" -ne "1" ]; then
    echo
    echo "Usage: git cloud create <local repo path>"
    echo
    echo "Create a new repo in the cloud repotree and clone it locally."
    echo ""
    exit 0
fi

if [ -z "$GIT_CLOUD_ROOT" ]; then
    echo "Git cloud createrepo must be run inside a git cloud repotree." >&2
    exit 1
fi
if [ -z "$REMOTE_REPOTREE" ]; then
    echo ".git-cloud did not define REMOTE_REPOTREE"
    exit 1
fi

REPOPATH=$(realpath -m --relative-to "$GIT_CLOUD_ROOT" "${1%.git}")
cd "$GIT_CLOUD_ROOT"

REMOTE_REPOTREE_HOST="${REMOTE_REPOTREE%%:*}"
REMOTE_REPOTREE_PATH="${REMOTE_REPOTREE#*:}"
RPATH="${REMOTE_REPOTREE_PATH}/${REPOPATH}.git"

${GIT_SSH_COMMAND} "${REMOTE_REPOTREE_HOST}" bash -c "echo -n \"\"; mkdir -p \"${RPATH}\" && cd \"${RPATH}\" && git init --bare --initial-branch=main ."

git-cloud-clonerepo "$REPOPATH"
