#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

if [ "$1" == "describe" ]; then
   echo "Create snapshots of all repos in a repotree."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud snaptree"
    echo
    echo "Create snapshots of all repos in a repotree."
    echo
    exit 0
fi

internal-git-cloud-load-keys

echo "== Looping through all repos"
find . -name ".git" -prune | while read LINE; do
    DIR=$(dirname "$LINE")
    echo "= Syncing: $DIR"
    ( cd "$DIR"
      git-cloud-snapshot
    )
done
