#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

if [ "$1" == "describe" ]; then
   echo "Clone a single cloud repo into the local directory."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git-cloud clone <origin repo> [<sync repo>] [snapshot branch] [clone into path]"
    echo
    echo "Clone a single cloud repo into the local directory."
    echo
    exit 0
fi

REPO=$1
if [ -z "$2" ]; then
    SYNC_REPO=$1
else
    SYNC_REPO=$2
fi
if [ -z "$3" ]; then
    BRANCH="${GIT_CLOUD_SNAPSHOT_BRANCH_PREFIX}-$(hostname)"
else
    BRANCH="$3"
fi
if [ -z "$4" ]; then
    REPONAME=$(basename "$REPO" .git)
    DEST="./$REPONAME"
else
    DEST="$4"
    REPONAME=$(basename "$DEST")
fi

if [ ! -e "$REPONAME" ]; then
    git clone "$REPO" "$DEST"
fi
cd "$DEST"

if ! git rev-parse HEAD >& /dev/null; then
    echo "== Cloned repository is empty, creating and pushing empty initial commit."
    git branch -m main
    git commit -m "Initial commit" --allow-empty
    git push --set-upstream origin main
fi

if ! git remote get-url "${GIT_CLOUD_REMOTE_NAME}" >& /dev/null; then
    git remote add "${GIT_CLOUD_REMOTE_NAME}" "$SYNC_REPO"
fi
