#!/bin/bash

set -e

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"
source internal-git-cloud-connshare

CONNSHARE="ask"
while [ 1 == 1 ]; do
    if [ "$1" == "--cs-ask" ]; then
        CONNSHARE="ask"
        shift 1
    elif [ "$1" == "--cs-auto" ]; then
        CONNSHARE="auto"
        shift 1
    elif [ "$1" == "--cs-off" ]; then
        CONNSHARE="off"
        shift 1
    else
        break
    fi
done

if [ "$1" == "describe" ]; then
   echo "Run git pull on all repos in a cloud repotree."
   exit 0
elif [ "$1" == "help" ]; then
    echo
    echo "Usage: git cloud pull"
    echo
    echo
    echo "    --cs-ask (default): set up ssh connection sharing, but ask each time it is used (safer on multiuser machines)"
    echo
    echo "    --cs-auto: set up ssh connection sharing, and skip passwords (unsafe if someone else can access the socket)."
    echo
    echo "    --cs-off: don't set up ssh connection sharing"
    echo
    echo "Run git pull on all repos in a cloud repotree."
    echo
    exit 0
fi

ssh-agent bash -c '

  check_key() {
    SEARCH=$(ssh-add -L | grep " ${1//./\\\.}\$")
    if [ -z "$SEARCH" ]; then
        return 0
    else
        return 1
    fi
  }

  for PUBKEY in "'$GIT_CLOUD_SSHDIR'"/*.pub; do
    PRIVKEY=$(basename "$PUBKEY" .pub)
    if check_key ~/.ssh/git-autosync/"$PRIVKEY"; then
        echo "== Adding key: $PRIVKEY"
        ssh-add ~/.ssh/git-autosync/"$PRIVKEY"
    fi
  done

  find . -name ".git" -prune | while read LINE; do
    #setup_cloud_connshare "$CONNSHARE"
    REPOPATH=$(dirname "$LINE")
    TRACKING=$(git -C "$REPOPATH" rev-parse --abbrev-ref --symbolic-full-name @{u})
    REMOTE=$(git -C "$REPOPATH" remote get-url "${TRACKING%%/*}")
    CLOUD_REMOTE=$(git -C "$REPOPATH" remote get-url cloud)
    if [ "$REMOTE" == "$CLOUD_REMOTE" ]; then
        echo "== Pulling from: $REPOPATH"
        git -C "$REPOPATH" pull
    fi
  done
'

find . -name ".git" -prune | while read LINE; do
  REPOPATH=$(dirname "$LINE")
  TRACKING=$(git -C "$REPOPATH" rev-parse --abbrev-ref --symbolic-full-name @{u})
  REMOTE=$(git -C "$REPOPATH" remote get-url "${TRACKING%%/*}")
  CLOUD_REMOTE=$(git -C "$REPOPATH" remote get-url cloud)
  if [ "$REMOTE" != "$CLOUD_REMOTE" ]; then
      echo "== Pulling from: $REPOPATH"
      git -C "$REPOPATH" pull
  fi
done
