#!/bin/bash

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

CONNSHARE="$1"

check_key() {
  SEARCH=$(ssh-add -L | grep " ${1//./\\\.}\$")
  if [ -z "$SEARCH" ]; then
      return 0
  else
      return 1
  fi
}

for PUBKEY in "$GIT_CLOUD_SSHDIR"/*.pub; do
  PRIVKEY=$(basename "$PUBKEY" .pub)
  if check_key ~/.ssh/git-autosync/"$PRIVKEY"; then
      echo "== Adding key: $PRIVKEY"
      ssh-add ~/.ssh/git-autosync/"$PRIVKEY"
  fi
  if [ -n "$CONNSHARE" ]; then
      setup_cloud_connshare "$PRIVKEY" "$CONNSHARE"
  fi

done
