#!/bin/bash

CONFDIR=$(git-cloud confdir)
source "${CONFDIR}/config"

check_key() {
  SEARCH=$(ssh-add -L | grep " ${1//./\\\.}\$")
  if [ -z "$SEARCH" ]; then
      return 0
  else
      return 1
  fi
}

find "$GIT_CLOUD_SSHDIR" -name "*.pub" | while read PUBKEY; do
  PRIVKEY=$(basename "$PUBKEY" .pub)
  if check_key ~/.ssh/git-cloud/"$PRIVKEY"; then
      echo "== Adding key: $PRIVKEY"
      ssh-add ~/.ssh/git-cloud/"$PRIVKEY"
  fi
done
