#!/bin/bash

set -e

source internal-git-cloud-read-config

if [ "$1" == "describe" ]; then
   echo "Configure a remote host for ssh connection-sharing for git-cloud."
   exit 0
elif [ "$1" == "help" -o "$#" -lt "1" ]; then
    echo
    echo "Usage: git cloud connshare [--remove] <remote>"
    echo
    echo "Configure a remote host for ssh connection-sharing for git-cloud"
    echo
    echo "Options:"
    echo "  --remove: remove the connection sharing setup for this remote"
    echo ""
    exit 0
fi

if [ "$1" == "--remove" ];then
  REMOVE="yes"
  shift 1
else
  REMOTE="no"
fi

REMOTE="$1"

if [ -n "${GIT_CLOUD_SSHDIR}" -a ! -e "$GIT_CLOUD_SSHDIR" ]; then
    mkdir -p "$GIT_CLOUD_SSHDIR"
    chmod go-rwx "$GIT_CLOUD_SSHDIR"
fi

if [ "$REMOVE" == "yes" ]; then
    if [ ! -e "${GIT_CLOUD_SSHDIR}/$REMOTE.cs" ]; then
        rm "${GIT_CLOUD_SSHDIR}/$REMOTE.cs"
    else
        echo "== No configuration for ssh connection sharing for $REMOTE exist."
    fi
else
    if [ ! -e "${GIT_CLOUD_SSHDIR}/$REMOTE.cs" ]; then
        echo "== Configuring $REMOTE to use ssh connection sharing."
        touch "${GIT_CLOUD_SSHDIR}/$REMOTE.cs"
    fi
fi

