#!/bin/bash

set -e

if [ "$1" == "--no-fetch" ]; then
    FETCH=false
    shift 1
else
    FETCH=true
fi

if [ -z "$1" ]; then
    REPO="$1"
else
    REPO="."
fi
cd "$REPO"

if [ "$FETCH" == "true" ]; then
    git fetch git-autosync
fi

REPODIR=$(git rev-parse --show-toplevel)
cd "$REPODIR"
REPONAME=$(basename "$REPODIR")

GIT=$(cat ~/".git-autosync/worktrees/$REPONAME/.git")
export GIT_DIR="${GIT#*: }"
git add -A
BRANCH="git-autosync-$(hostname)"
git diff --cached --stat .
