#!/bin/bash

set -e

if [ "$1" == "--no-fetch" ]; then
    FETCH=false
    shift 1
else
    FETCH=true
fi

if [ -z "$1" ]; then
    REPO="$1"
else
    REPO="."
fi
cd "$REPO"

REPODIR=$(git rev-parse --show-toplevel)
REPONAME=$(basename "$REPODIR")
cd "$REPODIR"

if [ "$FETCH" == "true" ]; then
    git fetch git-autosync
fi

GIT=$(cat ~/".git-autosync/worktrees/$REPONAME/.git")
export GIT_DIR="${GIT#*: }"
git add -A

for BRANCH in $(git branch -r -l 'git-autosync/git-autosync-*'); do
    BASE=$(basename "$BRANCH")
    #RELATIVE=$(git rev-list --left-right --count "HEAD...${BRANCH}")
    LAST_MSG=$(git log ${BRANCH} -1 --pretty=%B)
    if [ "${LAST_MSG#git-autosync}" != "${LAST_MSG}" ]; then
        LAST_BRANCH="[$(cut -d\  -f5 <<<"$LAST_MSG")]"
        TIMESTAMP="at $(cut -d\  -f6- <<<"$LAST_MSG")"
    else
        LAST_BRANCH="[??] (msg: $(head -n 1 <<<"$LAST_MSG"))"
        TIMESTAMP=""
    fi
    printf "== %s from %s %s\n" "$BASE" "$LAST_BRANCH" "$TIMESTAMP"
    git diff --name-status "${BRANCH}"
    printf "\n"
done
